### PR TITLE
fix: change default to playground

### LINKED ISSUE #26: Change default to playground instead of experimental

### PR DESCRIPTION
**Pull request by tianhaoz95**
Fixes #26

### CODE REVIEW

File: test/fixtures/payloads/basic/index.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+const prOpenedPayload: Record<string, unknown> = prGeneric;
+prOpenedPayload["action"] = "opened";
+
+const prReopenedPayload: Record<string, unknown> = prGeneric;
+prOpenedPayload["action"] = "reopened";
+
+const prSynchronizePayload: Record<string, unknown> = prGeneric;
+prOpenedPayload["action"] = "synchronize";
+
+export { prOpenedPayload, prReopenedPayload, prSynchronizePayload};
```
Comment (tianhaoz95) [inline test/fixtures/payloads/basic/index.ts:12]: Codacy found an issue: [file should end with a newline](https://app.codacy.com/manual/tianhaoz/approveman/pullRequest?prid=6091206)

**Comment by tianhaoz95** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/tianhaoz/approveman/pullRequest?prid=6091206&bid=19944375)

**Comment by tianhaoz95** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/tianhaoz/approveman/pullRequest?prid=6091206&bid=19944375)

File: test/fixtures/payloads/basic/index.ts (hunk 1 above)
Comment (tianhaoz95) [inline test/fixtures/payloads/basic/index.ts:12]: Codacy found an issue: [file should end with a newline](https://app.codacy.com/manual/tianhaoz/approveman/pullRequest?prid=6091206)
